const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    LOADING_STATUS_TRUE : "LOADING_STATUS_TRUE",
    LOADING_STATUS_FALSE : "LOADING_STATUS_FALSE"
}

export default ActionTypes